/**
 * Kenya Cyber Threat Intelligence Dataset
 * 
 * Realistic cyber threat entries based on known incidents affecting
 * Kenyan infrastructure, government systems, and citizens.
 * Used for AI training baseline and dashboard feed population.
 * 
 * References: KE-CIRT/CC advisories, CAK reports, DPA 2019 violations
 */

import type { IncidentType, DataProtectionImpact, Region, ThreatLevel } from '@/types';

export interface KenyaCyberThreatRecord {
    id: string;
    title: string;
    description: string;
    type: IncidentType;
    threatLevel: ThreatLevel;
    targetSystem: string;
    targetSector: string;
    region: Region;
    locationName: string;
    coordinates: [number, number];
    mitreAttackId: string;
    mitreTechnique: string;
    dataProtectionImpact: DataProtectionImpact;
    affectedCitizens: number;
    iocIndicators: string[];
    dpaViolation?: string;
    aiConfidence: number;
    sources: string[];
}

// ============================================================
// 50+ Realistic Kenya Cyber Threat Records
// ============================================================

export const KENYA_CYBER_THREATS: KenyaCyberThreatRecord[] = [
    // ---- PHISHING CAMPAIGNS ----
    {
        id: 'KCT-001',
        title: 'eCitizen Portal Credential Harvesting Campaign',
        description: 'Sophisticated phishing campaign impersonating eCitizen.go.ke portal targeting government employees and citizens seeking online services. Fake domains registered via .ke registrar.',
        type: 'PHISHING',
        threatLevel: 'CRITICAL',
        targetSystem: 'eCitizen Portal',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1566.001',
        mitreTechnique: 'Spearphishing Attachment',
        dataProtectionImpact: 'CREDENTIALS_LEAKED',
        affectedCitizens: 45000,
        iocIndicators: ['domain:ecitizen-verify.co.ke', 'hash:a3f2b8c9d1e4f5a6b7c8d9e0f1a2b3c4', 'ip:185.234.72.0/24'],
        dpaViolation: 'Section 41 - Unauthorized collection of personal data',
        aiConfidence: 96,
        sources: ['KE-CIRT/CC', 'OSINT', 'Citizen Reports'],
    },
    {
        id: 'KCT-002',
        title: 'KRA iTax Phishing - Tax Refund Scam',
        description: 'SMS and email phishing claiming KRA tax refunds, redirecting to fake iTax portal. Harvests KRA PINs, ID numbers, and bank details.',
        type: 'PHISHING',
        threatLevel: 'HIGH',
        targetSystem: 'KRA iTax',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Westlands',
        coordinates: [-1.2672, 36.8078],
        mitreAttackId: 'T1566.002',
        mitreTechnique: 'Spearphishing Link',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 23000,
        iocIndicators: ['domain:kra-refund-portal.com', 'domain:itax-verify.ke', 'ip:91.215.85.0/24'],
        dpaViolation: 'Section 43 - Processing without consent',
        aiConfidence: 94,
        sources: ['KRA Security Team', 'OSINT', 'Dark Web Intel'],
    },
    {
        id: 'KCT-003',
        title: 'M-Pesa Agent Verification Phishing',
        description: 'Social engineering campaign targeting M-Pesa agents with fake "verification required" SMS messages leading to credential theft.',
        type: 'PHISHING',
        threatLevel: 'HIGH',
        targetSystem: 'M-Pesa Infrastructure',
        targetSector: 'Financial',
        region: 'MOMBASA',
        locationName: 'Mombasa CBD',
        coordinates: [-4.0435, 39.6682],
        mitreAttackId: 'T1598.003',
        mitreTechnique: 'Spearphishing Service',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 8500,
        iocIndicators: ['sms:+254700XXXXXX', 'domain:mpesa-verify-agent.com', 'hash:e7f8a9b0c1d2e3f4a5b6c7d8'],
        aiConfidence: 92,
        sources: ['Safaricom Security', 'CAK', 'Citizen Reports'],
    },
    {
        id: 'KCT-004',
        title: 'NHIF Benefits Portal Impersonation',
        description: 'Phishing website mimicking the NHIF self-service portal to steal member IDs, national IDs, and banking credentials.',
        type: 'PHISHING',
        threatLevel: 'MEDIUM',
        targetSystem: 'NHIF Portal',
        targetSector: 'Healthcare',
        region: 'KISUMU',
        locationName: 'Kisumu Central',
        coordinates: [-0.0917, 34.7680],
        mitreAttackId: 'T1566.003',
        mitreTechnique: 'Spearphishing via Service',
        dataProtectionImpact: 'HEALTH_RECORDS',
        affectedCitizens: 12000,
        iocIndicators: ['domain:nhif-benefits-claim.co.ke', 'ip:103.75.190.0/24'],
        dpaViolation: 'Section 44 - Processing of health data without safeguards',
        aiConfidence: 89,
        sources: ['NHIF ICT', 'KE-CIRT/CC'],
    },
    {
        id: 'KCT-005',
        title: 'Huduma Centre Appointment Scam',
        description: 'Fraudulent SMS campaigns offering priority Huduma Namba appointments in exchange for personal data and small mobile payments.',
        type: 'PHISHING',
        threatLevel: 'MEDIUM',
        targetSystem: 'Huduma Centers',
        targetSector: 'Government',
        region: 'NAKURU',
        locationName: 'Nakuru Town',
        coordinates: [-0.3031, 36.0800],
        mitreAttackId: 'T1566.002',
        mitreTechnique: 'Spearphishing Link',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 5200,
        iocIndicators: ['domain:huduma-booking.com', 'sms:+254711XXXXXX'],
        aiConfidence: 87,
        sources: ['ICT Ministry', 'Citizen Reports'],
    },

    // ---- RANSOMWARE ----
    {
        id: 'KCT-006',
        title: 'LOCKBIT 4.0 Attack on KPLC Grid Systems',
        description: 'Ransomware deployment targeting Kenya Power control systems. SCADA network partially encrypted, causing load-shedding disruptions in multiple counties.',
        type: 'RANSOMWARE',
        threatLevel: 'CRITICAL',
        targetSystem: 'KPLC Grid Control',
        targetSector: 'Energy',
        region: 'NAIROBI',
        locationName: 'Industrial Area',
        coordinates: [-1.3246, 36.8433],
        mitreAttackId: 'T1486',
        mitreTechnique: 'Data Encrypted for Impact',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 2000000,
        iocIndicators: ['hash:d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9', 'domain:lockbit4-ransom.onion', 'ip:45.153.240.0/22'],
        aiConfidence: 98,
        sources: ['KPLC SOC', 'KE-CIRT/CC', 'Network Logs'],
    },
    {
        id: 'KCT-007',
        title: 'BlackCat Ransomware - Mombasa Port Authority',
        description: 'ALPHV/BlackCat ransomware variant targeting Kenya Ports Authority logistics systems, disrupting cargo manifests and vessel tracking.',
        type: 'RANSOMWARE',
        threatLevel: 'CRITICAL',
        targetSystem: 'Kenya Ports Authority',
        targetSector: 'Transport',
        region: 'MOMBASA',
        locationName: 'Port Reitz',
        coordinates: [-4.0733, 39.6347],
        mitreAttackId: 'T1486',
        mitreTechnique: 'Data Encrypted for Impact',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 50000,
        iocIndicators: ['hash:b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6', 'domain:blackcat-leak.onion'],
        aiConfidence: 95,
        sources: ['KPA Security', 'INTERPOL IGCI'],
    },
    {
        id: 'KCT-008',
        title: 'Conti Variant Targeting Nairobi Hospital Network',
        description: 'Healthcare-focused ransomware encrypting patient records across private hospital network in Nairobi. Ransom demanded in cryptocurrency.',
        type: 'RANSOMWARE',
        threatLevel: 'HIGH',
        targetSystem: 'Hospital EHR Systems',
        targetSector: 'Healthcare',
        region: 'NAIROBI',
        locationName: 'Westlands',
        coordinates: [-1.2672, 36.8078],
        mitreAttackId: 'T1486',
        mitreTechnique: 'Data Encrypted for Impact',
        dataProtectionImpact: 'HEALTH_RECORDS',
        affectedCitizens: 180000,
        iocIndicators: ['hash:f0e1d2c3b4a5f6e7d8c9b0a1f2e3d4c5'],
        dpaViolation: 'Section 44 - Failure to protect health data',
        aiConfidence: 91,
        sources: ['Hospital ICT', 'KE-CIRT/CC'],
    },

    // ---- DATA BREACHES ----
    {
        id: 'KCT-009',
        title: 'eCitizen Platform Major Data Breach',
        description: 'Unauthorized access to eCitizen database exposing passport details, birth certificates, and national ID data of Kenyan citizens.',
        type: 'DATA_BREACH',
        threatLevel: 'CRITICAL',
        targetSystem: 'eCitizen Portal',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1530',
        mitreTechnique: 'Data from Cloud Storage',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 700000,
        iocIndicators: ['ip:194.26.29.0/24', 'hash:a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6'],
        dpaViolation: 'Section 41 - Breach of data security obligations',
        aiConfidence: 97,
        sources: ['KE-CIRT/CC', 'Dark Web Intel', 'International Partners'],
    },
    {
        id: 'KCT-010',
        title: 'CBK Mobile Banking Data Exfiltration',
        description: 'Sophisticated SQL injection chain targeting Central Bank-connected mobile banking APIs, exfiltrating customer financial records.',
        type: 'DATA_BREACH',
        threatLevel: 'CRITICAL',
        targetSystem: 'CBK Core Banking',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1190',
        mitreTechnique: 'Exploit Public-Facing Application',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 350000,
        iocIndicators: ['ip:91.132.92.0/24', 'domain:cbk-api-shadow.com'],
        dpaViolation: 'Section 43 - Unauthorized processing of financial data',
        aiConfidence: 93,
        sources: ['CBK SOC', 'Financial ISAC'],
    },
    {
        id: 'KCT-011',
        title: 'IEBC Voter Database Leak',
        description: 'Partial exfiltration of voter registration data from IEBC systems including biometric references, names, and polling station assignments.',
        type: 'DATA_BREACH',
        threatLevel: 'HIGH',
        targetSystem: 'IEBC Voter Register',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Eastleigh',
        coordinates: [-1.2764, 36.8392],
        mitreAttackId: 'T1005',
        mitreTechnique: 'Data from Local System',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 500000,
        iocIndicators: ['hash:c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9'],
        dpaViolation: 'Section 41 - Failure to implement appropriate safeguards',
        aiConfidence: 88,
        sources: ['IEBC ICT', 'OSINT'],
    },
    {
        id: 'KCT-012',
        title: 'University Student Records Exposure',
        description: 'Misconfigured cloud storage exposing student records from multiple Kenyan universities including transcripts and financial aid data.',
        type: 'DATA_BREACH',
        threatLevel: 'MEDIUM',
        targetSystem: 'University Management Systems',
        targetSector: 'Government',
        region: 'ELDORET',
        locationName: 'Eldoret Town',
        coordinates: [0.5143, 35.2698],
        mitreAttackId: 'T1530',
        mitreTechnique: 'Data from Cloud Storage',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 85000,
        iocIndicators: ['url:s3-bucket-ke-edu-2026.amazonaws.com'],
        aiConfidence: 85,
        sources: ['OSINT', 'Academic CERT'],
    },

    // ---- MALWARE ----
    {
        id: 'KCT-013',
        title: 'Trojan on Safaricom Internal Network',
        description: 'Remote access Trojan (RAT) detected on Safaricom internal engineering workstations, potentially exfiltrating network configurations.',
        type: 'MALWARE',
        threatLevel: 'CRITICAL',
        targetSystem: 'Safaricom Core Network',
        targetSector: 'Telecom',
        region: 'NAIROBI',
        locationName: 'Westlands',
        coordinates: [-1.2672, 36.8078],
        mitreAttackId: 'T1059.001',
        mitreTechnique: 'Command and Scripting Interpreter: PowerShell',
        dataProtectionImpact: 'CREDENTIALS_LEAKED',
        affectedCitizens: 30000000,
        iocIndicators: ['hash:e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3', 'c2:command-relay-ke.ddns.net', 'ip:77.91.124.0/24'],
        aiConfidence: 96,
        sources: ['Safaricom SOC', 'Threat Intel Partner'],
    },
    {
        id: 'KCT-014',
        title: 'Wiper Malware on JKIA Control Systems',
        description: 'Destructive wiper malware detected attempting to corrupt JKIA flight management and baggage handling systems.',
        type: 'MALWARE',
        threatLevel: 'CRITICAL',
        targetSystem: 'JKIA Control Systems',
        targetSector: 'Transport',
        region: 'NAIROBI',
        locationName: 'Industrial Area',
        coordinates: [-1.3246, 36.8433],
        mitreAttackId: 'T1485',
        mitreTechnique: 'Data Destruction',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 500000,
        iocIndicators: ['hash:d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0', 'mutex:GlobalWiperKE2026'],
        aiConfidence: 97,
        sources: ['KAA Security', 'NIS', 'Network Logs'],
    },
    {
        id: 'KCT-015',
        title: 'Banking Trojan Targeting Equity Bank Customers',
        description: 'Android banking Trojan distributed via fake Equity Mobile app on third-party stores, intercepting OTP codes and M-Banking credentials.',
        type: 'MALWARE',
        threatLevel: 'HIGH',
        targetSystem: 'Equity Mobile Banking',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1409',
        mitreTechnique: 'Credential Access via Input Capture',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 17000,
        iocIndicators: ['apk:com.equity.mobile.fake', 'hash:a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7'],
        dpaViolation: 'Section 43 - Unauthorized processing',
        aiConfidence: 90,
        sources: ['Equity SOC', 'Google Play Protect', 'CAK'],
    },
    {
        id: 'KCT-016',
        title: 'Rootkit in SGR Operations Network',
        description: 'Kernel-level rootkit discovered on SGR railway operations server providing persistent backdoor access for state-sponsored actors.',
        type: 'MALWARE',
        threatLevel: 'HIGH',
        targetSystem: 'SGR Operations',
        targetSector: 'Transport',
        region: 'MOMBASA',
        locationName: 'Mombasa CBD',
        coordinates: [-4.0435, 39.6682],
        mitreAttackId: 'T1014',
        mitreTechnique: 'Rootkit',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 200000,
        iocIndicators: ['hash:f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6', 'driver:sgr_sys_helper.sys'],
        aiConfidence: 88,
        sources: ['Kenya Railways', 'NIS', 'International Partners'],
    },

    // ---- DDoS ATTACKS ----
    {
        id: 'KCT-017',
        title: 'Volumetric DDoS on NTSA TIMS Portal',
        description: 'Sustained 1.2Tbps volumetric DDoS attack on NTSA TIMS (Transport Integrated Management System) disrupting vehicle registration and licensing.',
        type: 'DDOS',
        threatLevel: 'HIGH',
        targetSystem: 'NTSA TIMS Portal',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1498.001',
        mitreTechnique: 'Network Denial of Service: Direct Network Flood',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 150000,
        iocIndicators: ['botnet:Mirai-KE-variant', 'ip:185.220.101.0/24'],
        aiConfidence: 94,
        sources: ['NTSA ICT', 'ISP Partners', 'KE-CIRT/CC'],
    },
    {
        id: 'KCT-018',
        title: 'Application Layer DDoS on NSE Trading Platform',
        description: 'HTTP flood targeting Nairobi Securities Exchange causing trading halts and investor panic during peak hours.',
        type: 'DDOS',
        threatLevel: 'CRITICAL',
        targetSystem: 'NSE Trading Platform',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1499.003',
        mitreTechnique: 'Application Exhaustion Flood',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 75000,
        iocIndicators: ['ip:23.227.38.0/24', 'ua:Bot/DDoS-KE-2026'],
        aiConfidence: 92,
        sources: ['NSE SOC', 'CMA', 'Network Logs'],
    },
    {
        id: 'KCT-019',
        title: 'DDoS Campaign Against Kenyan ISPs',
        description: 'Coordinated DDoS attacks against multiple Kenyan Internet Service Providers affecting internet connectivity nationwide.',
        type: 'DDOS',
        threatLevel: 'HIGH',
        targetSystem: 'National Fiber Backbone',
        targetSector: 'Telecom',
        region: 'NAIROBI',
        locationName: 'Industrial Area',
        coordinates: [-1.3246, 36.8433],
        mitreAttackId: 'T1498.002',
        mitreTechnique: 'Reflection Amplification',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 5000000,
        iocIndicators: ['ip:45.95.169.0/24', 'protocol:DNS-amplification'],
        aiConfidence: 91,
        sources: ['KIXP', 'ISP Consortium', 'CAK'],
    },

    // ---- APT (Advanced Persistent Threats) ----
    {
        id: 'KCT-020',
        title: 'APT-KE-001 SANDSTORM - State Ministry Espionage',
        description: 'Long-running APT campaign attributed to foreign state actors targeting Ministry of Foreign Affairs email servers for diplomatic intelligence.',
        type: 'APT',
        threatLevel: 'CRITICAL',
        targetSystem: 'MFA Email Infrastructure',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1078.004',
        mitreTechnique: 'Valid Accounts: Cloud Accounts',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 5000,
        iocIndicators: ['c2:apt-ke-sandstorm.ddns.net', 'hash:c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0', 'ip:203.0.113.0/24'],
        aiConfidence: 97,
        sources: ['NIS', 'International SIGINT', 'Network Logs'],
    },
    {
        id: 'KCT-021',
        title: 'APT-KE-002 BUSHFIRE - SEACOM Cable Surveillance',
        description: 'Persistent access to SEACOM submarine cable landing station in Mombasa for traffic interception and metadata collection.',
        type: 'APT',
        threatLevel: 'CRITICAL',
        targetSystem: 'SEACOM Landing Station',
        targetSector: 'Telecom',
        region: 'MOMBASA',
        locationName: 'Nyali',
        coordinates: [-4.0181, 39.7121],
        mitreAttackId: 'T1040',
        mitreTechnique: 'Network Sniffing',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 10000000,
        iocIndicators: ['implant:seacom-intercept-v2', 'ip:198.51.100.0/24'],
        aiConfidence: 95,
        sources: ['NIS', 'SEACOM Operations', 'International Partners'],
    },
    {
        id: 'KCT-022',
        title: 'APT-KE-003 MONSOON - Defense Network Intrusion',
        description: 'APT group maintaining persistence in KDF military communications network through compromised firmware in network equipment.',
        type: 'APT',
        threatLevel: 'CRITICAL',
        targetSystem: 'KDF Communications',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Eastleigh',
        coordinates: [-1.2764, 36.8392],
        mitreAttackId: 'T1195.003',
        mitreTechnique: 'Supply Chain Compromise: Compromise Hardware Supply Chain',
        dataProtectionImpact: 'CREDENTIALS_LEAKED',
        affectedCitizens: 25000,
        iocIndicators: ['firmware:modified-cisco-ios-ke', 'c2:monsoon-c2.example.com'],
        aiConfidence: 93,
        sources: ['KDF Cyber Command', 'NIS', 'SIGINT'],
    },
    {
        id: 'KCT-023',
        title: 'APT Targeting Geothermal Energy SCADA',
        description: 'Sophisticated intrusion into Olkaria Geothermal Plant SCADA systems potentially aimed at disrupting national power generation.',
        type: 'APT',
        threatLevel: 'HIGH',
        targetSystem: 'Geothermal Plant SCADA',
        targetSector: 'Energy',
        region: 'NAKURU',
        locationName: 'Nakuru Town',
        coordinates: [-0.3031, 36.0800],
        mitreAttackId: 'T1071.001',
        mitreTechnique: 'Application Layer Protocol: Web Protocols',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 3000000,
        iocIndicators: ['ip:162.247.72.0/24', 'hash:b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3'],
        aiConfidence: 89,
        sources: ['KenGen SOC', 'NIS', 'ICS-CERT'],
    },

    // ---- INSIDER THREATS ----
    {
        id: 'KCT-024',
        title: 'IFMIS Insider Data Theft',
        description: 'Privileged government employee exfiltrating procurement data from Integrated Financial Management Information System for competitive intelligence.',
        type: 'INSIDER_THREAT',
        threatLevel: 'HIGH',
        targetSystem: 'IFMIS',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1567.002',
        mitreTechnique: 'Exfiltration to Cloud Storage',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 10000,
        iocIndicators: ['user:admin-ifmis-compromised', 'cloud:gdrive-exfil-ke'],
        dpaViolation: 'Section 42 - Breach of confidentiality by data processor',
        aiConfidence: 86,
        sources: ['IFMIS Audit', 'DCI Cyber Unit'],
    },
    {
        id: 'KCT-025',
        title: 'Telco Employee Selling Customer Data',
        description: 'Telecommunications company employee selling subscriber location data, call records, and M-Pesa transaction histories to third parties.',
        type: 'INSIDER_THREAT',
        threatLevel: 'HIGH',
        targetSystem: 'Telco CRM Systems',
        targetSector: 'Telecom',
        region: 'NAIROBI',
        locationName: 'Westlands',
        coordinates: [-1.2672, 36.8078],
        mitreAttackId: 'T1078',
        mitreTechnique: 'Valid Accounts',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 250000,
        iocIndicators: ['user:insider-telco-2026', 'exfil:usb-device-detected'],
        dpaViolation: 'Section 41(d) - Processing beyond authorized purpose',
        aiConfidence: 91,
        sources: ['Telco Internal Audit', 'CAK', 'DCI'],
    },
    {
        id: 'KCT-026',
        title: 'Bank Teller Credential Abuse',
        description: 'Multiple branch tellers using shared admin credentials to access customer accounts beyond their authorization, extracting balances and transaction history.',
        type: 'INSIDER_THREAT',
        threatLevel: 'MEDIUM',
        targetSystem: 'Core Banking Systems',
        targetSector: 'Financial',
        region: 'KISUMU',
        locationName: 'Kisumu Central',
        coordinates: [-0.0917, 34.7680],
        mitreAttackId: 'T1078.001',
        mitreTechnique: 'Valid Accounts: Default Accounts',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 4500,
        iocIndicators: ['user:shared-admin-branch-ksm'],
        dpaViolation: 'Section 43 - Processing without data subject consent',
        aiConfidence: 84,
        sources: ['Bank Internal Audit', 'CBK Supervision'],
    },

    // ---- IDENTITY THEFT ----
    {
        id: 'KCT-027',
        title: 'Digital ID System Identity Fraud Ring',
        description: 'Criminal network using stolen biometric data to create fraudulent Digital IDs, enabling SIM swap fraud and unauthorized financial access.',
        type: 'IDENTITY_THEFT',
        threatLevel: 'CRITICAL',
        targetSystem: 'Digital ID System',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Eastleigh',
        coordinates: [-1.2764, 36.8392],
        mitreAttackId: 'T1588.002',
        mitreTechnique: 'Obtain Capabilities: Tool',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 15000,
        iocIndicators: ['biometric:stolen-fingerprint-db', 'sim:bulk-swap-detected'],
        dpaViolation: 'Section 41 - Breach of biometric data security',
        aiConfidence: 92,
        sources: ['DCI', 'CAK', 'Telco Partners'],
    },
    {
        id: 'KCT-028',
        title: 'Synthetic Identity Fraud - Mobile Loans',
        description: 'Fraudsters creating synthetic identities by combining real and fake data to obtain mobile loans from digital lending platforms.',
        type: 'IDENTITY_THEFT',
        threatLevel: 'HIGH',
        targetSystem: 'Digital Lending Platforms',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'Kibera',
        coordinates: [-1.3127, 36.7885],
        mitreAttackId: 'T1589.001',
        mitreTechnique: 'Gather Victim Identity Information: Credentials',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 8000,
        iocIndicators: ['pattern:synthetic-id-cluster-ke'],
        aiConfidence: 87,
        sources: ['Digital Lenders Association', 'CRB Kenya'],
    },
    {
        id: 'KCT-029',
        title: 'SIM Swap Fraud Ring - Garissa',
        description: 'Organized SIM swap fraud ring operating from Garissa region, targeting elderly citizens with M-Pesa accounts through social engineering of telecom agents.',
        type: 'IDENTITY_THEFT',
        threatLevel: 'MEDIUM',
        targetSystem: 'Telecom SIM Management',
        targetSector: 'Telecom',
        region: 'GARISSA',
        locationName: 'Garissa Town',
        coordinates: [-0.4569, 39.6403],
        mitreAttackId: 'T1556',
        mitreTechnique: 'Modify Authentication Process',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 3200,
        iocIndicators: ['pattern:sim-swap-garissa-ring'],
        aiConfidence: 83,
        sources: ['DCI Garissa', 'CAK', 'Citizen Reports'],
    },

    // ---- MORE PHISHING ----
    {
        id: 'KCT-030',
        title: 'WhatsApp Business Impersonation - County Govts',
        description: 'Fake WhatsApp Business accounts impersonating county government offices to collect personal information under guise of county services.',
        type: 'PHISHING',
        threatLevel: 'MEDIUM',
        targetSystem: 'County Government Digital Services',
        targetSector: 'Government',
        region: 'TURKANA',
        locationName: 'Lodwar',
        coordinates: [3.1190, 35.5970],
        mitreAttackId: 'T1566.003',
        mitreTechnique: 'Spearphishing via Service',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 6800,
        iocIndicators: ['wa-business:+254722XXXXXX'],
        aiConfidence: 81,
        sources: ['County ICT', 'Citizen Reports'],
    },

    // ---- MORE DATA BREACHES ----
    {
        id: 'KCT-031',
        title: 'HELB Student Loan Data Exposure',
        description: 'Higher Education Loans Board database compromised, exposing student loan data, repayment histories, and employer details.',
        type: 'DATA_BREACH',
        threatLevel: 'HIGH',
        targetSystem: 'HELB Portal',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1213',
        mitreTechnique: 'Data from Information Repositories',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 420000,
        iocIndicators: ['ip:146.70.92.0/24', 'darkweb:helb-dump-2026'],
        dpaViolation: 'Section 41 - Inadequate security measures',
        aiConfidence: 90,
        sources: ['HELB ICT', 'Dark Web Intel'],
    },

    // ---- MORE MALWARE ----
    {
        id: 'KCT-032',
        title: 'Cryptominer on Government Cloud',
        description: 'Cryptocurrency mining malware discovered running on government cloud infrastructure, consuming taxpayer-funded compute resources.',
        type: 'MALWARE',
        threatLevel: 'MEDIUM',
        targetSystem: 'Government Cloud Infrastructure',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Industrial Area',
        coordinates: [-1.3246, 36.8433],
        mitreAttackId: 'T1496',
        mitreTechnique: 'Resource Hijacking',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 0,
        iocIndicators: ['pool:ke-gov-miner.pool.com', 'hash:a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4'],
        aiConfidence: 86,
        sources: ['ICT Ministry', 'Cloud Provider'],
    },

    // ---- MORE DDoS ----
    {
        id: 'KCT-033',
        title: 'DDoS on Immigration e-Services',
        description: 'Distributed denial-of-service attack disrupting online passport and visa application services during peak travel season.',
        type: 'DDOS',
        threatLevel: 'HIGH',
        targetSystem: 'Immigration e-Services',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1499.002',
        mitreTechnique: 'Service Exhaustion Flood',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 200000,
        iocIndicators: ['botnet:ke-ddos-variant-3', 'ip:185.100.87.0/24'],
        aiConfidence: 93,
        sources: ['Immigration Dept', 'KE-CIRT/CC'],
    },

    // ---- MORE RANSOMWARE ----
    {
        id: 'KCT-034',
        title: 'Akira Ransomware - County Government Systems',
        description: 'Akira ransomware encrypting county government financial systems across multiple counties simultaneously.',
        type: 'RANSOMWARE',
        threatLevel: 'HIGH',
        targetSystem: 'County IFMIS Systems',
        targetSector: 'Government',
        region: 'ELDORET',
        locationName: 'Eldoret Town',
        coordinates: [0.5143, 35.2698],
        mitreAttackId: 'T1486',
        mitreTechnique: 'Data Encrypted for Impact',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 100000,
        iocIndicators: ['hash:d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7', 'domain:akira-leak-ke.onion'],
        aiConfidence: 89,
        sources: ['County ICT', 'KE-CIRT/CC'],
    },

    // ---- MORE APT ----
    {
        id: 'KCT-035',
        title: 'APT-KE-004 SAVANNA - Oil Pipeline Monitoring',
        description: 'State-sponsored threat actor maintaining persistent access to oil pipeline monitoring systems in Turkana for strategic intelligence.',
        type: 'APT',
        threatLevel: 'CRITICAL',
        targetSystem: 'Oil Pipeline Monitoring',
        targetSector: 'Energy',
        region: 'TURKANA',
        locationName: 'Lodwar',
        coordinates: [3.1190, 35.5970],
        mitreAttackId: 'T1195.002',
        mitreTechnique: 'Supply Chain Compromise: Compromise Software Supply Chain',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 500000,
        iocIndicators: ['c2:savanna-ke-apt.onion', 'backdoor:pipeline-mon-v2.dll'],
        aiConfidence: 94,
        sources: ['NIS', 'Energy Ministry', 'International Partners'],
    },

    // ---- MORE INSIDER THREATS ----
    {
        id: 'KCT-036',
        title: 'Immigration Officer Selling Passport Data',
        description: 'Immigration department officer selling passport application data and travel histories to private investigators and criminal networks.',
        type: 'INSIDER_THREAT',
        threatLevel: 'HIGH',
        targetSystem: 'Immigration Database',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1530',
        mitreTechnique: 'Data from Cloud Storage',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 50000,
        iocIndicators: ['user:insider-immigration-2026'],
        dpaViolation: 'Section 42 - Breach of confidentiality',
        aiConfidence: 88,
        sources: ['Internal Affairs', 'DCI'],
    },

    // ---- MORE IDENTITY THEFT ----
    {
        id: 'KCT-037',
        title: 'Deepfake Voice KYC Bypass',
        description: 'Criminals using AI-generated deepfake voices to bypass voice-based KYC verification at banks and telecoms.',
        type: 'IDENTITY_THEFT',
        threatLevel: 'HIGH',
        targetSystem: 'Banking KYC Systems',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1589.003',
        mitreTechnique: 'Gather Victim Identity Information: Employee Names',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 2100,
        iocIndicators: ['ai-tool:deepfake-voice-ke', 'pattern:kyc-bypass-cluster'],
        aiConfidence: 85,
        sources: ['Banking ISAC', 'AI Threat Research'],
    },

    // ---- CROSS-BORDER ----
    {
        id: 'KCT-038',
        title: 'Cross-Border M-Pesa Fraud Network',
        description: 'International fraud network exploiting M-Pesa Global cross-border payment system for money laundering and terrorist financing.',
        type: 'IDENTITY_THEFT',
        threatLevel: 'CRITICAL',
        targetSystem: 'M-Pesa Global',
        targetSector: 'Financial',
        region: 'MANDERA',
        locationName: 'Mandera Town',
        coordinates: [3.9366, 41.8550],
        mitreAttackId: 'T1583.003',
        mitreTechnique: 'Acquire Infrastructure: Virtual Private Server',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 45000,
        iocIndicators: ['txn:cross-border-anomaly-cluster', 'ip:169.239.128.0/24'],
        aiConfidence: 91,
        sources: ['CBK FIU', 'INTERPOL', 'Safaricom'],
    },

    // ---- ADDITIONAL THREATS ----
    {
        id: 'KCT-039',
        title: 'Credential Stuffing on eCitizen Services',
        description: 'Large-scale credential stuffing attack using leaked databases targeting eCitizen single-sign-on services.',
        type: 'DATA_BREACH',
        threatLevel: 'HIGH',
        targetSystem: 'eCitizen SSO',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1110.004',
        mitreTechnique: 'Brute Force: Credential Stuffing',
        dataProtectionImpact: 'CREDENTIALS_LEAKED',
        affectedCitizens: 120000,
        iocIndicators: ['ip-range:185.220.0.0/16', 'tool:credential-list-ke-2026'],
        aiConfidence: 93,
        sources: ['eCitizen SOC', 'KE-CIRT/CC'],
    },
    {
        id: 'KCT-040',
        title: 'Supply Chain - Compromised IT Vendor Update',
        description: 'Trojanized software update from major Kenyan government IT vendor distributing backdoor to multiple ministry networks.',
        type: 'MALWARE',
        threatLevel: 'CRITICAL',
        targetSystem: 'Government IT Infrastructure',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Westlands',
        coordinates: [-1.2672, 36.8078],
        mitreAttackId: 'T1195.002',
        mitreTechnique: 'Supply Chain Compromise',
        dataProtectionImpact: 'CREDENTIALS_LEAKED',
        affectedCitizens: 75000,
        iocIndicators: ['update-server:compromised-vendor-ke.com', 'hash:c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8'],
        aiConfidence: 96,
        sources: ['NIS', 'ICT Ministry', 'Vendor Audit'],
    },
    {
        id: 'KCT-041',
        title: 'Watering Hole Attack on Judiciary Portal',
        description: 'Judiciary e-Filing portal compromised to serve malware to legal professionals accessing case management systems.',
        type: 'MALWARE',
        threatLevel: 'HIGH',
        targetSystem: 'Judiciary e-Filing',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1189',
        mitreTechnique: 'Drive-by Compromise',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 25000,
        iocIndicators: ['domain:judiciary-efiling-ke.com', 'exploit-kit:ke-water-v3'],
        aiConfidence: 88,
        sources: ['Judiciary ICT', 'KE-CIRT/CC'],
    },
    {
        id: 'KCT-042',
        title: 'Medical IoT Device Compromise - Kenyatta Hospital',
        description: 'Internet-connected medical devices at Kenyatta National Hospital compromised, potentially allowing manipulation of patient monitoring data.',
        type: 'MALWARE',
        threatLevel: 'CRITICAL',
        targetSystem: 'Kenyatta Hospital EHR',
        targetSector: 'Healthcare',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1584.005',
        mitreTechnique: 'Compromise Infrastructure: Botnet',
        dataProtectionImpact: 'HEALTH_RECORDS',
        affectedCitizens: 500000,
        iocIndicators: ['device:iot-meddev-ke-botnet', 'ip:103.75.190.128/25'],
        dpaViolation: 'Section 44 - Processing of health data',
        aiConfidence: 94,
        sources: ['KNH ICT', 'Medical Device CERT'],
    },
    {
        id: 'KCT-043',
        title: 'DNS Hijacking - Kenya Government Domains',
        description: 'DNS records for multiple .go.ke domains hijacked to redirect government traffic through adversary-controlled servers.',
        type: 'APT',
        threatLevel: 'CRITICAL',
        targetSystem: 'Government DNS Infrastructure',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1584.002',
        mitreTechnique: 'Compromise Infrastructure: DNS Server',
        dataProtectionImpact: 'CREDENTIALS_LEAKED',
        affectedCitizens: 2000000,
        iocIndicators: ['dns:hijacked-go-ke-records', 'ip:185.215.113.0/24'],
        aiConfidence: 95,
        sources: ['KENIC', 'KE-CIRT/CC', 'NIS'],
    },
    {
        id: 'KCT-044',
        title: 'Fake Mobile Banking Apps on Play Store',
        description: 'Multiple fraudulent mobile banking applications masquerading as legitimate Kenyan bank apps to harvest credentials.',
        type: 'PHISHING',
        threatLevel: 'HIGH',
        targetSystem: 'Mobile Banking Ecosystem',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1566.003',
        mitreTechnique: 'Spearphishing via Service',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 35000,
        iocIndicators: ['apk:fake-kcb-mobile-2026', 'apk:fake-cooperative-bank'],
        aiConfidence: 90,
        sources: ['Google Play Protect', 'Banking ISAC', 'CAK'],
    },
    {
        id: 'KCT-045',
        title: 'Traffic Camera Network Breach',
        description: 'Unauthorized access to Nairobi traffic camera network, with footage being sold on dark web for surveillance of VIP movements.',
        type: 'DATA_BREACH',
        threatLevel: 'HIGH',
        targetSystem: 'Traffic Management CCTV',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'CBD',
        coordinates: [-1.2864, 36.8172],
        mitreAttackId: 'T1125',
        mitreTechnique: 'Video Capture',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 1000000,
        iocIndicators: ['darkweb:nairobi-cam-feed-sale', 'ip:31.13.195.0/24'],
        aiConfidence: 87,
        sources: ['NPS Traffic', 'Dark Web Intel'],
    },
    {
        id: 'KCT-046',
        title: 'Airtel Kenya Customer Data Sale',
        description: 'Bulk customer PII from Airtel Kenya discovered for sale on dark web forums including phone numbers, ID data, and location history.',
        type: 'DATA_BREACH',
        threatLevel: 'HIGH',
        targetSystem: 'Airtel Kenya Systems',
        targetSector: 'Telecom',
        region: 'MOMBASA',
        locationName: 'Likoni',
        coordinates: [-4.0889, 39.6647],
        mitreAttackId: 'T1567',
        mitreTechnique: 'Exfiltration Over Web Service',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 340000,
        iocIndicators: ['darkweb:airtel-ke-dump', 'forum:underground-data-ke'],
        dpaViolation: 'Section 41 - Breach notification obligations',
        aiConfidence: 89,
        sources: ['CAK', 'Dark Web Intel', 'Airtel Audit'],
    },
    {
        id: 'KCT-047',
        title: 'Water Utility SCADA Manipulation',
        description: 'Cyber intrusion into Nairobi Water SCADA systems attempting to manipulate water treatment chemical dosing parameters.',
        type: 'APT',
        threatLevel: 'CRITICAL',
        targetSystem: 'Nairobi Water SCADA',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Industrial Area',
        coordinates: [-1.3246, 36.8433],
        mitreAttackId: 'T0855',
        mitreTechnique: 'Unauthorized Command Message',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 4000000,
        iocIndicators: ['plc:modbus-anomaly-detected', 'ip:45.77.65.0/24'],
        aiConfidence: 96,
        sources: ['NWS Security', 'ICS-CERT', 'NIS'],
    },
    {
        id: 'KCT-048',
        title: 'QR Code Phishing in Nairobi Restaurants',
        description: 'Malicious QR codes placed over legitimate payment QR codes in restaurants, redirecting M-Pesa payments to fraudster accounts.',
        type: 'PHISHING',
        threatLevel: 'MEDIUM',
        targetSystem: 'M-Pesa QR Payments',
        targetSector: 'Financial',
        region: 'NAIROBI',
        locationName: 'Westlands',
        coordinates: [-1.2672, 36.8078],
        mitreAttackId: 'T1566.002',
        mitreTechnique: 'Spearphishing Link',
        dataProtectionImpact: 'FINANCIAL_DATA',
        affectedCitizens: 1200,
        iocIndicators: ['qr:malicious-redirect-pattern'],
        aiConfidence: 78,
        sources: ['Safaricom', 'DCI', 'Merchant Reports'],
    },
    {
        id: 'KCT-049',
        title: 'Fuel Distribution Network Ransomware',
        description: 'Ransomware attack targeting Kenya Pipeline Company fuel distribution management systems causing supply chain disruptions.',
        type: 'RANSOMWARE',
        threatLevel: 'HIGH',
        targetSystem: 'Fuel Distribution Network',
        targetSector: 'Energy',
        region: 'MOMBASA',
        locationName: 'Port Reitz',
        coordinates: [-4.0733, 39.6347],
        mitreAttackId: 'T1486',
        mitreTechnique: 'Data Encrypted for Impact',
        dataProtectionImpact: 'NONE',
        affectedCitizens: 2000000,
        iocIndicators: ['hash:f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9', 'ransom-note:kpc-encrypted.txt'],
        aiConfidence: 92,
        sources: ['KPC Security', 'Energy Ministry', 'KE-CIRT/CC'],
    },
    {
        id: 'KCT-050',
        title: 'Social Media Data Harvesting for Electoral Manipulation',
        description: 'Large-scale scraping of Kenyan social media profiles to build voter influence databases for targeted political disinformation.',
        type: 'DATA_BREACH',
        threatLevel: 'HIGH',
        targetSystem: 'Social Media Platforms',
        targetSector: 'Government',
        region: 'NAIROBI',
        locationName: 'Eastleigh',
        coordinates: [-1.2764, 36.8392],
        mitreAttackId: 'T1593',
        mitreTechnique: 'Search Open Websites/Domains',
        dataProtectionImpact: 'PII_EXPOSED',
        affectedCitizens: 5000000,
        iocIndicators: ['scraper:ke-voter-profiler', 'infra:cloud-scraping-ke'],
        dpaViolation: 'Section 41 - Unlawful processing for profiling',
        aiConfidence: 86,
        sources: ['ODPC', 'OSINT', 'International Partners'],
    },
];

// Helper to get a random subset of threats
export function getRandomThreats(count: number = 20): KenyaCyberThreatRecord[] {
    const shuffled = [...KENYA_CYBER_THREATS].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, Math.min(count, shuffled.length));
}

// Get threats by type
export function getThreatsByType(type: IncidentType): KenyaCyberThreatRecord[] {
    return KENYA_CYBER_THREATS.filter(t => t.type === type);
}

// Get threats by region
export function getThreatsByRegion(region: Region): KenyaCyberThreatRecord[] {
    return KENYA_CYBER_THREATS.filter(t => t.region === region);
}

// Get critical threats only
export function getCriticalThreats(): KenyaCyberThreatRecord[] {
    return KENYA_CYBER_THREATS.filter(t => t.threatLevel === 'CRITICAL');
}

// Get threats with DPA violations
export function getDPAViolations(): KenyaCyberThreatRecord[] {
    return KENYA_CYBER_THREATS.filter(t => t.dpaViolation !== undefined);
}
