// PDF Export utility for NC4 Compliance Reports
'use client'

import jsPDF from 'jspdf'

interface ReportData {
    title: string
    classification: 'UNCLASSIFIED' | 'CONFIDENTIAL' | 'SECRET' | 'TOP SECRET'
    date: string
    author: string
    agency: string
    incident: {
        id: string
        title: string
        type: string
        severity: string
        status: string
        location?: string
        description: string
        detectedAt: string
        targetAsset?: string
        attackVector?: string
    }
    actions: {
        protocol: string
        status: string
        executedAt: string
    }[]
    recommendations: string[]
    hash: string
}

export function generatePDF(data: ReportData): jsPDF {
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    let y = 20

    // Helper for centered text
    const centerText = (text: string, yPos: number, fontSize: number = 12) => {
        doc.setFontSize(fontSize)
        const textWidth = doc.getTextWidth(text)
        doc.text(text, (pageWidth - textWidth) / 2, yPos)
    }

    // Classification header
    doc.setFillColor(0, 0, 0)
    doc.rect(0, 0, pageWidth, 15, 'F')
    doc.setTextColor(255, 0, 0)
    doc.setFontSize(14)
    centerText(`// ${data.classification} //`, 10, 14)
    doc.setTextColor(0, 0, 0)
    y = 30

    // Title
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    centerText('NC4 COMPLIANCE REPORT', y)
    y += 10

    // Subtitle
    doc.setFontSize(12)
    doc.setFont('helvetica', 'normal')
    centerText('National Cyber Command - Incident Response Report', y)
    y += 20

    // Report metadata
    doc.setFontSize(10)
    doc.text(`Report ID: ${data.incident.id}`, 20, y)
    doc.text(`Date: ${data.date}`, pageWidth - 60, y)
    y += 7
    doc.text(`Author: ${data.author}`, 20, y)
    doc.text(`Agency: ${data.agency}`, pageWidth - 60, y)
    y += 15

    // Section: Incident Details
    doc.setFillColor(0, 100, 0)
    doc.rect(20, y, pageWidth - 40, 8, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.text('INCIDENT DETAILS', 25, y + 6)
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'normal')
    y += 15

    const incidentDetails = [
        ['Title:', data.incident.title],
        ['Type:', data.incident.type],
        ['Severity:', data.incident.severity],
        ['Status:', data.incident.status],
        ['Location:', data.incident.location || 'N/A'],
        ['Detected At:', data.incident.detectedAt],
        ['Target Asset:', data.incident.targetAsset || 'N/A'],
        ['Attack Vector:', data.incident.attackVector || 'N/A'],
    ]

    for (const [label, value] of incidentDetails) {
        doc.setFont('helvetica', 'bold')
        doc.text(label, 25, y)
        doc.setFont('helvetica', 'normal')
        doc.text(value, 70, y)
        y += 7
    }

    y += 5

    // Description
    doc.setFont('helvetica', 'bold')
    doc.text('Description:', 25, y)
    y += 5
    doc.setFont('helvetica', 'normal')
    const descLines = doc.splitTextToSize(data.incident.description, pageWidth - 50)
    doc.text(descLines, 25, y)
    y += descLines.length * 5 + 10

    // Section: Actions Taken
    doc.setFillColor(0, 0, 100)
    doc.rect(20, y, pageWidth - 40, 8, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.text('ACTIONS TAKEN', 25, y + 6)
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'normal')
    y += 15

    for (const action of data.actions) {
        doc.text(`• ${action.protocol}`, 25, y)
        doc.text(`Status: ${action.status}`, 120, y)
        y += 7
    }
    y += 5

    // Section: Recommendations
    if (data.recommendations.length > 0) {
        doc.setFillColor(100, 50, 0)
        doc.rect(20, y, pageWidth - 40, 8, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFont('helvetica', 'bold')
        doc.text('RECOMMENDATIONS', 25, y + 6)
        doc.setTextColor(0, 0, 0)
        doc.setFont('helvetica', 'normal')
        y += 15

        for (const rec of data.recommendations) {
            const recLines = doc.splitTextToSize(`• ${rec}`, pageWidth - 50)
            doc.text(recLines, 25, y)
            y += recLines.length * 5 + 3
        }
    }

    // Footer with hash
    y = doc.internal.pageSize.getHeight() - 30
    doc.setDrawColor(0, 0, 0)
    doc.line(20, y, pageWidth - 20, y)
    y += 7
    doc.setFontSize(8)
    doc.text(`Document Hash (SHA-256): ${data.hash}`, 20, y)
    y += 5
    doc.text('This document is compliant with Kenya Computer Misuse and Cybercrime Act (2018)', 20, y)
    y += 5
    doc.text(`Generated by NCTIRS v1.3.0 | ${new Date().toISOString()}`, 20, y)

    // Classification footer
    doc.setFillColor(0, 0, 0)
    doc.rect(0, doc.internal.pageSize.getHeight() - 10, pageWidth, 10, 'F')
    doc.setTextColor(255, 0, 0)
    doc.setFontSize(10)
    centerText(`// ${data.classification} //`, doc.internal.pageSize.getHeight() - 3, 10)

    return doc
}

// Download PDF helper
export function downloadPDF(data: ReportData, filename?: string) {
    const doc = generatePDF(data)
    const defaultFilename = `NC4_Report_${data.incident.id}_${new Date().toISOString().split('T')[0]}.pdf`
    doc.save(filename || defaultFilename)
}

// Preview PDF in new window
export function previewPDF(data: ReportData) {
    const doc = generatePDF(data)
    const pdfDataUri = doc.output('datauristring')
    window.open(pdfDataUri, '_blank')
}
