// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use local file for CLI operations (migrations, db push)
    // Runtime uses libsql adapter in lib/db.ts
    url: "file:./dev.db",
  },
});

